language: crystal

install:
- shards install

script:
  - crystal spec
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    all_branch: true
  local_dir: docs
