language: crystal

install:
- shards install

script:
  - crystal spec
  - crystal docs

deploy:
  provider: pages
  keep_history: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master 
    
  local_dir: docs
